name: Build Stremio Skip Patcher Monorepo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create complete folder structure
      run: |
        echo "This workflow is a placeholder in this repo."
